CREATE TABLE IF NOT EXISTS `sys_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL UNIQUE COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '密码（BCrypt 加密）',
  `real_name` VARCHAR(64) DEFAULT NULL COMMENT '姓名',
  `role` VARCHAR(32) NOT NULL COMMENT '角色：ADMIN/TEACHER/STUDENT',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 禁用，1 启用',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

